### ISSUE TITLE
'olderthan-x-minutes' is not a valid value for FetchOperator.

### ISSUE THREAD

**Issue by denious** [TheCRMLab/CRMIQ#8]
Error executing RetrieveMultiple in a Dynamics CRM 365 on-prem environment. Full stack below.

This operator is supported since CRM 2015:
https://msdn.microsoft.com/en-us/library/gg334216(v=crm.7).aspx.

`"System.InvalidOperationException: There is an error in XML document (40, 50). ---> System.InvalidOperationException: Instance validation error: 'olderthan-x-minutes' is not a valid value for FetchOperator.
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderFetchXmlExpression.Read10_FetchOperator(String s)
  at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderFetchXmlExpression.Read12_FetchCondition(Boolean isNullable, Boolean checkType)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderFetchXmlExpression.Read14_FetchFilter(Boolean isNullable, Boolean checkType)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderFetchXmlExpression.Read16_FetchEntity(Boolean isNullable, Boolean checkType)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderFetchXmlExpression.Read19_FetchXmlExpression(Boolean isNullable, Boolean checkType)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderFetchXmlExpression.Read20_fetch()
   --- End of inner exception stack trace ---
  at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events)
   at System.Xml.Serialization.XmlSerializer.Deserialize(TextReader textReader)
   at Cobalt.Components.CrmIQ.Plugin.FetchXmlExpression.Deserialize(String xml)
   at Cobalt.Components.CrmIQ.Plugin.PluginAdapter.UpdateFetchExpressionWithCrmIQ(ITracingService tracer, FetchExpression expression)
   at Cobalt.Components.CrmIQ.Plugin.PluginAdapter.Execute(IServiceProvider serviceProvider)"
`

**Comment by TheCRMLab** [comment]
This has been resolved in the latest update for version 1.3
